// <auto-generated />
namespace GoToCinema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RowNameString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RowNameString));
        
        string IMigrationMetadata.Id
        {
            get { return "202106231308293_RowNameString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
